const $ = selector => document.querySelector(selector);
const money = cents => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100);
const labels = { RECEIVED: 'Recebido', PAYMENT_PENDING: 'Pagamento pendente', PAID: 'Pago', PREPARING: 'Em preparo', OUT_FOR_DELIVERY: 'Saiu para entrega', COMPLETED: 'Finalizado', CANCELLED: 'Cancelado' };
let orders = [];
async function request(url, options = {}) { const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const body = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(body?.error || 'Não foi possível concluir a operação.'); return body; }
function showAdmin() { $('[data-login]').hidden = true; $('[data-admin-content]').hidden = false; refresh(); }
function renderOrders() { $('[data-orders]').innerHTML = orders.length ? orders.map(order => `<article class="admin-order"><div class="order-top"><div><strong>#${order.number}</strong><span>${new Date(order.createdAt).toLocaleString('pt-BR')}</span></div><select data-order-status="${order.id}">${Object.entries(labels).map(([value, label]) => `<option value="${value}" ${order.orderStatus === value ? 'selected' : ''}>${label}</option>`).join('')}</select></div><h3>${order.customerName}</h3><p>${order.phone} · ${order.deliveryMethod === 'DELIVERY' ? `${order.address}, ${order.addressNumber} - ${order.neighborhood}` : 'Retirada no local'}</p><ul>${order.items.map(item => `<li>${item.quantity}x ${item.productName} (${money(item.unitPriceCents)})</li>`).join('')}</ul><div class="order-total"><span>${order.paymentStatus === 'APPROVED' ? 'Pagamento aprovado' : 'Pagamento pendente'}</span><strong>${money(order.totalCents)}</strong></div></article>`).join('') : '<p>Nenhum pedido ainda.</p>'; }
async function refresh() { try { orders = await request('/api/admin/orders'); renderOrders(); renderProducts(); const settings = await request('/api/admin/settings'); $('[data-settings-form] input').value = settings.deliveryFeeCents; } catch (error) { $('[data-orders]').innerHTML = `<p class="form-message">${error.message}</p>`; } }
async function renderProducts() { const products = await request('/api/admin/products'); $('[data-products]').innerHTML = products.map(product => `<div class="admin-product"><div><strong>${product.name}</strong><span>${money(product.priceCents)} · ${product.active ? 'Ativo' : 'Inativo'}</span></div><button class="btn btn-secondary" data-edit-product="${product.id}">Editar</button></div>`).join(''); }
$('[data-login-form]').addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/admin/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); showAdmin(); } catch (error) { $('[data-login-message]').textContent = error.message; } });
$('[data-logout]').addEventListener('click', async () => { await request('/api/admin/logout', { method: 'POST' }); location.reload(); });
$('[data-refresh]').addEventListener('click', refresh);
document.addEventListener('change', async event => { if (!event.target.dataset.orderStatus) return; try { await request(`/api/admin/orders/${event.target.dataset.orderStatus}/status`, { method: 'PATCH', body: JSON.stringify({ status: event.target.value }) }); await refresh(); } catch (error) { alert(error.message); } });
$('[data-product-form]').addEventListener('submit', async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); data.priceCents = Number(data.priceCents); data.active = event.currentTarget.active.checked; const id = data.id; delete data.id; try { await request(id ? `/api/admin/products/${id}` : '/api/admin/products', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(data) }); $('[data-product-message]').textContent = 'Produto salvo.'; event.currentTarget.reset(); await renderProducts(); } catch (error) { $('[data-product-message]').textContent = error.message; } });
$('[data-clear-product]').addEventListener('click', () => $('[data-product-form]').reset());
document.addEventListener('click', async event => { const button = event.target.closest('[data-edit-product]'); if (!button) return; const product = (await request('/api/admin/products')).find(item => item.id === button.dataset.editProduct); for (const [key, value] of Object.entries(product)) { const field = $('[data-product-form]').elements[key]; if (field) field.type === 'checkbox' ? field.checked = value : field.value = value; } });
$('[data-settings-form]').addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/admin/settings', { method: 'PATCH', body: JSON.stringify({ deliveryFeeCents: Number(new FormData(event.currentTarget).get('deliveryFeeCents')) }) }); $('[data-settings-message]').textContent = 'Taxa salva.'; } catch (error) { $('[data-settings-message]').textContent = error.message; } });
request('/api/admin/me').then(showAdmin).catch(() => { $('[data-login]').hidden = false; });
setInterval(() => { if (!$('[data-admin-content]').hidden) refresh(); }, 15000);
