ALTER TABLE "Product" ADD COLUMN "category" TEXT NOT NULL DEFAULT 'Geral';
ALTER TABLE "Product" ADD COLUMN "stock" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN "manualSoldOut" BOOLEAN NOT NULL DEFAULT false;
